name: test-git2
description: ''
version: 0.0.1
author: admin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testgit2
  parentArtefactID: adminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-11-28 12:23:47'
pipelines:
  pipelines/test2:
    name: test2
    description: ''
    author: admin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-11-28 12:23:47'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-11-28 12:23:47'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-11-28T12:23:47.534906Z'
  name: plibMaven
  version: 8.14.0
  id: '574370813'
  createdAt: '2025-11-28T12:23:47.534906Z'
  type: plibMaven
- modifiedAt: '2025-11-28T12:23:47.534906Z'
  name: plibPypi
  version: 2.1.5
  id: '1946187646'
  createdAt: '2025-11-28T12:23:47.534906Z'
  type: plibPypi
projectDependencies:
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/ErhizwiH_team_2/WjBkwjII_project_5.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-11-28 12:23:29'
  '4':
    projectUID: 4
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/ErhizwiH_team_2/WjBkwjII_project_4.git&subPath=
    version: 0.2.52
    isDefault: true
    author: null
    createdAt: '2025-11-28 12:23:29'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
